server:
  port: 8771


#服务的名称
spring:
  zipkin:
    base-url: http://192.168.107.30:9411/
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 192.168.107.30
    port: 5672
    username: guest
    password: guest

env: test2019
